name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name:
      ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest] # [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Add msbuild to PATH (Windows)
      if: matrix.platform == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.6.0

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      shell: bash
      run: |
        cmake -E make_directory ${{github.workspace}}/build
        curl -L https://github.com/copasi/copasi-dependencies/releases/download/v4.31.240/${{ matrix.platform }}.zip -o ${{ matrix.platform }}.zip
        unzip ${{ matrix.platform }}.zip -d dependencies

    - name: Patch dependencies (windows)
      shell: bash
      if: matrix.platform == 'windows-latest'
      working-directory: ${{github.workspace}}/dependencies/lib/cmake
      run: |
        sed -i 's|D:/a/copasi-dependencies/copasi-dependencies/install/|${_IMPORT_PREFIX}/|g'  *.cmake

    - name: Patch dependencies (ubuntu)
      shell: bash
      if: matrix.platform == 'ubuntu-latest'
      working-directory: ${{github.workspace}}/dependencies/lib/cmake
      run: |
        sed -i 's|/home/runner/work/copasi-dependencies/copasi-dependencies/install/|${_IMPORT_PREFIX}/|g'  *.cmake

    - name: Patch dependencies (mac)
      shell: bash
      if: matrix.platform == 'macos-latest'
      working-directory: ${{github.workspace}}/dependencies/lib/cmake
      run: |
        sed -i '.tmp' 's|/Users/runner/work/copasi-dependencies/copasi-dependencies/install/|${_IMPORT_PREFIX}/|g'  *.cmake

    - name: Download COPASI
      shell: bash
      run: |
        git clone https://github.com/copasi/COPASI
        cmake -E make_directory ${{github.workspace}}/build_copasi

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/COPASi
      run: ./gitTools/UpdateCopasiVersion

    - name: Configure COPASI
      shell: bash
      working-directory: ${{github.workspace}}/build_copasi
      run: cmake $GITHUB_WORKSPACE/COPASI -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOPASI_INSTALL_C_API=ON -DBUILD_GUI=OFF -DCOPASI_DEPENDENCY_DIR=../dependencies/ -DCMAKE_INSTALL_PREFIX=../dependencies/

    - name: Build COPASI
      shell: bash
      working-directory: ${{github.workspace}}/build_copasi
      run: cmake --build . --config $BUILD_TYPE

    - name: Install COPASI
      shell: bash
      working-directory: ${{github.workspace}}/build_copasi
      run: cmake --build . --config $BUILD_TYPE --target install

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UI_DEPS=OFF -DLIBSBML_DIR=../dependencies/lib/cmake -DCMAKE_INSTALL_PREFIX=../install/ -DCOPASI_DEPENDENCY_DIR=../dependencies/

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target install

    - name: binary archive
      uses: actions/upload-artifact@v2
      with:
        name:
          ${{ matrix.platform }}
        path: ${{github.workspace}}/install/*
        retention-days: 1
        if-no-files-found: error
